/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.projetoCatalogo.view;

import br.com.projetoCatalogo.DAO.SerieDAO;
import br.com.projetoCatalogo.controller.CadastroSeriesController;
import br.com.projetoCatalogo.factory.ConnectionFactory;
import br.com.projetoCatalogo.model.Serie;
import com.sun.jdi.connect.spi.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Vinic
 */
public class TelaDeCadastroDeSeries extends javax.swing.JFrame {

    private final CadastroSeriesController controller;

   
    public TelaDeCadastroDeSeries() throws SQLException {
        initComponents();
        readTable();
        controller = new CadastroSeriesController(this);
        DefaultTableModel modelo = (DefaultTableModel) TableSeries.getModel();
        TableSeries.setRowSorter(new TableRowSorter(modelo));
        jTextFieldNomeSerie.setText("");
        jTextFieldPlataformaSerie.setText("");
        jTextFieldCategoriaSerie.setText("");
        jTextFieldTemporadaSerie.setText("");
        
        
    }
    
    public final void readTable() throws SQLException{
        
        DefaultTableModel modelo = (DefaultTableModel) TableSeries.getModel();
        modelo.setNumRows(0);
        SerieDAO seriedao = new SerieDAO();
        
        for(Serie serie: seriedao.read()){
            modelo.addRow(new Object[]{
                serie.getId(),
                serie.getNome(),
                serie.getPlataforma(),
                serie.getCategoria(),
                serie.getTemporadas()
            });
        }
    }

    public JTextField getjTextFieldCategoriaSerie() {
        return jTextFieldCategoriaSerie;
    }

    public void setjTextFieldCategoriaSerie(JTextField jTextFieldCategoriaSerie) {
        this.jTextFieldCategoriaSerie = jTextFieldCategoriaSerie;
    }

    public JTextField getjTextFieldNomeSerie() {
        return jTextFieldNomeSerie;
    }

    public void setjTextFieldNomeSerie(JTextField jTextFieldNomeSerie) {
        this.jTextFieldNomeSerie = jTextFieldNomeSerie;
    }

    public JTextField getjTextFieldPlataformaSerie() {
        return jTextFieldPlataformaSerie;
    }

    public void setjTextFieldPlataformaSerie(JTextField jTextFieldPlataformaSerie) {
        this.jTextFieldPlataformaSerie = jTextFieldPlataformaSerie;
    }

    public JTextField getjTextFieldTemporadaSerie() {
        return jTextFieldTemporadaSerie;
    }

    public void setjTextFieldTemporadaSerie(JTextField jTextFieldTemporadaSerie) {
        this.jTextFieldTemporadaSerie = jTextFieldTemporadaSerie;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNomeSerie = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTemporadaSerie = new javax.swing.JTextField();
        jTextFieldPlataformaSerie = new javax.swing.JTextField();
        jTextFieldCategoriaSerie = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableSeries = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jLabel1.setText("jLabel1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nome");

        jLabel3.setText("Plataforma");

        jLabel4.setText("Categoria");

        jTextFieldNomeSerie.setText("jTextField1");
        jTextFieldNomeSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeSerieActionPerformed(evt);
            }
        });

        jLabel5.setText("Temporadas");

        jTextFieldTemporadaSerie.setText("jTextField2");

        jTextFieldPlataformaSerie.setText("jTextField3");

        jTextFieldCategoriaSerie.setText("jTextField4");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldNomeSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPlataformaSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldCategoriaSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldTemporadaSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPlataformaSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTemporadaSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCategoriaSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 170));

        TableSeries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Plataforma", "Categoria", "Temporadas"
            }
        ));
        TableSeries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSeriesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableSeries);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 590, 250));

        jMenu3.setText("Menu");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try { 
            controller.salvarSeries();
            
            readTable();// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(TelaDeCadastroDeSeries.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldNomeSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeSerieActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       new TelaDeMenu().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
      Serie serie = new Serie();
      SerieDAO seriedao = new SerieDAO();
      
      int index = TableSeries.getSelectedRow();
        try {
            serie = seriedao.read().get(index);
            seriedao.delete(serie);
            readTable();
        } catch (SQLException ex) {
            Logger.getLogger(TelaDeCadastroDeSeries.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Serie serie = new Serie();
        SerieDAO seriedao = new SerieDAO();
        
        int index = TableSeries.getSelectedRow();//Retrona o numero da linha selecionada
        
        try {
            serie = seriedao.read().get(index);//Retorna o objeto dentro da ArrayList
            
            //Set as novas informacoes para o objeto selecionado
            serie.setNome(jTextFieldNomeSerie.getText());
            serie.setPlataforma(jTextFieldPlataformaSerie.getText());
            serie.setCategoria(jTextFieldCategoriaSerie.getText());
            serie.setTemporadas(jTextFieldTemporadaSerie.getText());
            //faz a alteracao no bd
            seriedao.update(serie);
            readTable();
        } catch (SQLException ex) {
            Logger.getLogger(TelaDeCadastroDeSeries.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TableSeriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSeriesMouseClicked
       Serie serie = new Serie();
       SerieDAO seriedao = new SerieDAO();
       
       int index = TableSeries.getSelectedRow();
       
        try {
            serie = seriedao.read().get(index);
            
            jTextFieldNomeSerie.setText(String.valueOf(serie.getNome()));
            jTextFieldPlataformaSerie.setText(String.valueOf(serie.getPlataforma()));
            jTextFieldCategoriaSerie.setText(String.valueOf(serie.getCategoria()));
            jTextFieldTemporadaSerie.setText(String.valueOf(serie.getTemporadas()));
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaDeCadastroDeSeries.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_TableSeriesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastroDeSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastroDeSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastroDeSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastroDeSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaDeCadastroDeSeries().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaDeCadastroDeSeries.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableSeries;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldCategoriaSerie;
    private javax.swing.JTextField jTextFieldNomeSerie;
    private javax.swing.JTextField jTextFieldPlataformaSerie;
    private javax.swing.JTextField jTextFieldTemporadaSerie;
    // End of variables declaration//GEN-END:variables
}
